### ISSUE TITLE
Forbid tabs.

### ISSUE THREAD

**Issue by Gurkenglas** [aelve/haskell-issues#19]
People keep having indentation errors on #haskell because they accidentally some tabs into their code. Make ghc complain about this, or find another way to stop this problem.

**Comment by gbaz** [comment]
-fwarn-tabs exists, but it isn't in -Wall. ¯_(ツ)_/¯

**Comment by neongreen** [comment]
GHC 7.10 [already complains](https://ghc.haskell.org/trac/ghc/ticket/9230) about tabs by default:

``` haskell
main = print    0
```

``` bash
$ ghc tab.hs
[1 of 1] Compiling Main             ( tab.hs, tab.o )

tab.hs:1:13: Warning: Tab character
Linking tab ...
```

**Comment by neongreen** [comment]
@Gurkenglas: can this issue be closed, or have I missed something?

**Comment by Gurkenglas** [comment]
From gbaz's comment, I thought it's not default. Perhaps some flashing signs are in order. With a button on ghc's output to enhance vision on the probable-to-be-a-problem warnings and perhaps illustrate the problems with some examples... should we make an issue out of that? Nah...
