### ISSUE TITLE
lpaste: Allow editing of titles

### ISSUE THREAD

**Issue by Gurkenglas** [aelve/haskell-issues#21]
This would be useful for finding a particular paste when browsing all pastes made under your name.

**Comment by neongreen** [comment]
https://github.com/chrisdone/lpaste/issues/28

**Comment by neongreen** [comment]
Interestingly, this should already work: https://github.com/chrisdone/lpaste/blob/bad90874d6052e817bd7163cbfdcab740bf7ff0b/src/Hpaste/Model/Paste.hs#L241. Yet it doesn't.

**Comment by neongreen** [comment]
I made a pull request to fix this: https://github.com/chrisdone/lpaste/pull/35.

**Comment by neongreen** [comment]
And it's been merged. Whoa, @chrisdone is fast.

**Comment by neongreen** [comment]
Deployed.

**Comment by Gurkenglas** [comment]
Yay! (You could have factored pasteTitle out of that case statement though)
