### ISSUE TITLE
This'll take a true Hufflepuff: Resolve these issues!

### ISSUE THREAD

**Issue by Gurkenglas** [aelve/haskell-issues#25]
> <Gurkenglas> puregreen, as quietly feared, already seems to have run out of his initial rush of enthusiastic diligence. Anyone feel up to the task of adding a little fuel to the part of the show where this is redirected to the right people?
> <Gurkenglas> (I suddenly understand all those shady cloaked people sitting in the corner of the tavern attracting adventurers.)
> <loofee> c
> * EvanR orders a mead
> <Gurkenglas> We need to find a way to get people doing our fetch quests. How does WoW do it?
> <EvanR> offering to pay them in money
> <EvanR> however small in quantity
> <Gurkenglas> Right, people must have connected issue trackers to mechanical turk before. Especially when the tasks are just "post this to the proper channels"
> <Gurkenglas> Doing that without rigor though might summon the economics fairy and lead to the least possible result that still has me paying money
> <Gurkenglas> Perhaps the bounty should be for actually getting it implemented, rather than posting it to the right channels?
> <Gurkenglas> That sounds like it would raise the appropriate bounty a hundredfold and summon salespeople and then everyone would be mad at me because I summoned salespeople
> <EvanR> gurkenglassssss jenkins

**Comment by neongreen** [comment]
> Perhaps the bounty should be for actually getting it implemented, rather than posting it to the right channels?

This already exists (e.g. bountysource) and it seems to work pretty poorly. A much more efficient way is hiring a competent Haskeller to do the work (redirecting things to right channels, taking maintainership of abandoned packages, implementing small things and making pull requests, etc), and this is totally what I'm going to do when I'm a CEO of a Haskell-based company, but currently I'm not.

> puregreen, as quietly feared, already seems to have run out of his initial rush of enthusiastic diligence

Well, and also I don't feel comfortable nagging people about issues when I know that I won't be able to answer questions about those issues. Take the “`under` + `_Wrapped`” one: I haven't ever used `_Wrapped`, so if somebody asks me “okay, what do you need this for?”, what am I supposed to say apart from “well um I'm asking for a friend”?

(Note that “be able to answer questions about” doesn't mean “like” – I don't think we need `.:`, for instance, but I'm still going to make a proposal about it and then count the votes.)

**Comment by Gurkenglas** [comment]
(I apologize for my impertinence, unless that's what spurred you into action :D)

**Comment by neongreen** [comment]
> that's what spurred you into action

Well, ma-aybe that was it. Maybe. Even if so, not going to admit it anyway.
