### ISSUE TITLE
lambdabot: Import (Data.Functor.$>)

### ISSUE THREAD

**Issue by Gurkenglas** [aelve/haskell-issues#30]
flip (<$)

**Comment by neongreen** [comment]
It's [already](http://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Functor.html#v:-36--62-) in `Data.Functor`.

**Comment by Gurkenglas** [comment]
Ah, L.hs just doesn't import it by default. That's something to fix, right?

**Comment by neongreen** [comment]
https://github.com/lambdabot/lambdabot/pull/141
